Dicegame
CS490-section03-group0/project3 pull request #76
Opened 2020-12-05 00:32 UTC by mhk8

2020-12-05 01:20 UTC, ak2253 approved these changes
Lgtm just fix the merge conflicts.

2020-12-05 01:23 UTC, dvkm requested changes

2020-12-05 01:23 UTC, dvkm commented on .eslintrc.js
> -    rules: {},
Any reason why you did this?

2020-12-05 01:23 UTC, dvkm commented on .idea/codeStyles/Project.xml
> +<component name="ProjectCodeStyleConfiguration">
add this file to .gitignore if you want to use the ide

2020-12-06 20:44 UTC, dvkm approved these changes

2020-12-06 21:08 UTC, merged